// frontend/src/views/Apps.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from "vue";
import { useBridge } from "@/plugins/qt-bridge";
import { useSignal } from "@/plugins/use-signal";
import { useDevicesStore } from "@/stores/devices";
import type { AppEntry } from "@/types/qt-bridge";

const bridge = useBridge();
const devices = useDevicesStore();
const on = useSignal();

const apps = ref<AppEntry[]>([]);
const ram = ref({ used: 0, total: 0 });
const storage = ref({ used: 0, total: 0 });
const search = ref("");
const showSystem = ref(true);
const showDisabled = ref(true);
const selectedPkg = ref<string | null>(null);

const filtered = computed(() =>
  apps.value
    .filter((a) => showSystem.value || a.type === "user")
    .filter((a) => showDisabled.value || a.status !== "disabled")
    .filter((a) => !search.value || a.package.toLowerCase().includes(search.value.toLowerCase()))
);

const selectedApp = computed(() => apps.value.find((a) => a.package === selectedPkg.value));

onMounted(() => {
  on(bridge.apps.listLoaded, (d) => {
    apps.value = d.apps;
    if (apps.value.length && !selectedPkg.value) selectedPkg.value = apps.value[0].package;
  });
  on(bridge.apps.appUpdated, (entry) => {
    const idx = apps.value.findIndex((a) => a.package === entry.package);
    if (idx >= 0) apps.value[idx] = entry;
  });
  on(bridge.apps.metersUpdated, (m) => {
    if (m.kind === "ram") ram.value = { used: m.used_mb, total: m.total_mb };
    else storage.value = { used: m.used_mb, total: m.total_mb };
  });

  if (devices.active) bridge.apps.loadAll(devices.active.serial);
});

watch(() => devices.active?.serial, (serial) => {
  if (serial) bridge.apps.loadAll(serial);
});

async function refresh() {
  if (devices.active) {
    apps.value = [];
    await bridge.apps.loadAll(devices.active.serial);
  }
}
async function uninstall(pkg: string) {
  await bridge.apps.uninstall(pkg);
}
async function toggleDisable(a: AppEntry) {
  if (a.status === "disabled") await bridge.apps.enablePackage(a.package);
  else await bridge.apps.disablePackage(a.package);
}

const ramPct = computed(() => ram.value.total ? Math.round(ram.value.used / ram.value.total * 100) : 0);
const storagePct = computed(() => storage.value.total ? Math.round(storage.value.used / storage.value.total * 100) : 0);

function fmtSize(mb: number) {
  return mb >= 1024 ? `${(mb / 1024).toFixed(1)} GB` : `${mb} MB`;
}
</script>

<template>
  <div class="page-header">
    <h1 class="page-title">Apps</h1>
    <span class="page-sub">{{ apps.length }} packages on device</span>
    <div class="page-actions">
      <button class="btn" :disabled="!devices.active" @click="refresh">Refresh</button>
    </div>
  </div>

  <section class="card">
    <div class="card-b grid gap-6 items-center" style="grid-template-columns: 1fr 1fr">
      <div class="stat">
        <div class="lbl">RAM</div>
        <div class="progress"><i :style="{ width: ramPct + '%' }"></i></div>
        <div class="val">Used {{ fmtSize(ram.used) }} / {{ fmtSize(ram.total) }}</div>
      </div>
      <div class="stat">
        <div class="lbl">Storage</div>
        <div class="progress"><i :style="{ width: storagePct + '%' }"></i></div>
        <div class="val">Used {{ fmtSize(storage.used) }} / {{ fmtSize(storage.total) }}</div>
      </div>
    </div>
  </section>

  <div class="grid gap-4 mt-4" style="grid-template-columns: minmax(0, 1.4fr) minmax(0, 1fr); height: calc(100vh - 360px); min-height: 480px;">
    <section class="card flex flex-col min-h-0">
      <div class="card-h">
        <div class="label">Packages</div>
        <div class="right"><span class="hint">{{ filtered.length }} apps</span></div>
      </div>
      <div class="toolbar-row">
        <input class="input flex-1" placeholder="Search by package…" v-model="search" />
        <label class="switch-label"><input type="checkbox" class="check" v-model="showSystem" /> Show system apps</label>
        <label class="switch-label"><input type="checkbox" class="check" v-model="showDisabled" /> Show disabled apps</label>
      </div>
      <div class="flex-1 overflow-auto">
        <table class="table">
          <thead><tr>
            <th class="sortable">Package name</th>
            <th class="col-status sortable">Status</th>
            <th class="col-type sortable">Type</th>
          </tr></thead>
          <tbody>
            <tr v-for="a in filtered" :key="a.package"
                :class="selectedPkg === a.package ? 'selected' : ''"
                class="cursor-pointer" @click="selectedPkg = a.package">
              <td><span class="font-mono">{{ a.package }}</span></td>
              <td>
                <span class="badge" :class="a.status === 'active' ? 'ok' : 'err'">
                  <span class="dot" :class="a.status === 'active' ? 'ok' : 'err'"></span>
                  {{ a.status === 'active' ? 'Active' : 'Disabled' }}
                </span>
              </td>
              <td><span class="hint">{{ a.type }}</span></td>
            </tr>
            <tr v-if="!filtered.length"><td colspan="3"><div class="empty">No apps.</div></td></tr>
          </tbody>
        </table>
      </div>
      <div class="card-f">
        <span class="hint">{{ apps.length }} apps loaded · {{ filtered.length }} shown</span>
      </div>
    </section>

    <aside class="card flex flex-col min-h-0 overflow-hidden">
      <div class="card-h"><div class="label">App details</div></div>
      <div v-if="selectedApp" class="card-b overflow-auto flex flex-col" style="padding:0">
        <div class="grid items-center gap-3" style="grid-template-columns: 50px 1fr; padding: 14px; border-bottom: 1px solid var(--border)">
          <div class="app-ico">{{ selectedApp.package.slice(0, 2).toUpperCase() }}</div>
          <div>
            <div class="font-semibold text-md break-words">{{ selectedApp.name || selectedApp.package }}</div>
            <div class="text-text2 text-sm font-mono break-all">{{ selectedApp.package }}</div>
            <div class="row" style="gap:6px; margin-top:6px">
              <span class="badge" :class="selectedApp.status === 'active' ? 'ok' : 'err'">
                <span class="dot" :class="selectedApp.status === 'active' ? 'ok' : 'err'"></span>
                {{ selectedApp.status }}
              </span>
              <span class="badge">{{ selectedApp.type }}</span>
            </div>
          </div>
        </div>

        <table class="detail-table">
          <tbody>
            <tr class="section-head"><td colspan="2">Storage</td></tr>
            <tr><td>APK path</td><td>{{ selectedApp.apk_path || "—" }}</td></tr>
          </tbody>
        </table>
      </div>
      <div v-else class="card-b flex-1"><div class="empty">Select an app.</div></div>
      <div class="card-f">
        <button v-if="selectedApp"
          class="btn small"
          @click="toggleDisable(selectedApp)"
        >{{ selectedApp.status === 'disabled' ? 'Enable' : 'Disable' }}</button>
        <button v-if="selectedApp && selectedApp.type === 'user'"
          class="btn btn-danger small" style="margin-left:auto"
          @click="uninstall(selectedApp.package)"
        >Uninstall</button>
      </div>
    </aside>
  </div>
</template>

// adb-helper_handoff_Claude_Design/project/modules/apps.jsx
// Module: Apps
const AppsModule = ({ ctx }) => {
  const { activeDevice, toast } = ctx;
  const [apps, setApps] = React.useState(MOCK_APPS);
  const [query, setQuery] = React.useState("");
  const [showSystem, setShowSystem] = React.useState(true);
  const [showDisabled, setShowDisabled] = React.useState(true);
  const [filter, setFilter] = React.useState("all");
  const [selected, setSelected] = React.useState(new Set());
  const [confirm, setConfirm] = React.useState(null);

  if (!activeDevice) return <NoDeviceEmpty label="Apps" />;

  const filtered = apps.filter((a) => {
    if (!showSystem && a.type === "system") return false;
    if (!showDisabled && a.status === "disabled") return false;
    if (filter === "user" && a.type !== "user") return false;
    if (filter === "system" && a.type !== "system") return false;
    const q = query.toLowerCase();
    return !q || a.name.toLowerCase().includes(q) || a.pkg.toLowerCase().includes(q);
  });

  const allSelected = filtered.length > 0 && filtered.every((a) => selected.has(a.pkg));
  const toggleAll = () => {
    if (allSelected) setSelected(new Set());else
    setSelected(new Set(filtered.map((a) => a.pkg)));
  };
  const toggleOne = (pkg) => {
    const next = new Set(selected);
    if (next.has(pkg)) next.delete(pkg);else next.add(pkg);
    setSelected(next);
  };

  const selectedApps = apps.filter((a) => selected.has(a.pkg));
  const anySystemSelected = selectedApps.some((a) => a.type === "system");
  const allDisabled = selectedApps.length > 0 && selectedApps.every((a) => a.status === "disabled");
  const allActive = selectedApps.length > 0 && selectedApps.every((a) => a.status === "active");

  const doAction = (kind) => {
    setApps((prev) => prev.map((a) => {
      if (!selected.has(a.pkg)) return a;
      if (kind === "uninstall" && a.type === "system") return a;
      if (kind === "uninstall") return null;
      if (kind === "disable") return { ...a, status: "disabled" };
      if (kind === "enable") return { ...a, status: "active" };
      return a;
    }).filter(Boolean));
    setSelected(new Set());
    setConfirm(null);
    const labels = { uninstall: "uninstalled", disable: "disabled", enable: "enabled" };
    toast({ kind: "success", title: `${selectedApps.length} app${selectedApps.length !== 1 ? "s" : ""} ${labels[kind]}` });
  };

  const ramTotal = activeDevice.ramTotal || 8192;
  const ramAvail = activeDevice.ramAvail || 3072;
  const ramUsed = ramTotal - ramAvail;
  const stTotal = activeDevice.storageTotal || 128000;
  const stAvail = activeDevice.storageAvail || 51200;
  const stUsed = stTotal - stAvail;

  return (
    <div className="card" style={{ display: "flex", flexDirection: "column", height: "100%", minHeight: 0 }}>
      <div className="usage-bars">
        <div className="usage-bar">
          <div className="top">
            <span className="lbl">RAM</span>
            <span className="val">Used {(ramUsed / 1024).toFixed(1)} GB / {(ramTotal / 1024).toFixed(1)} GB</span>
          </div>
          <div className="bar"><div className={`fill ${ramUsed / ramTotal > 0.85 ? "warn" : ""}`} style={{ width: `${ramUsed / ramTotal * 100}%` }} /></div>
        </div>
        <div className="usage-bar">
          <div className="top">
            <span className="lbl">Storage (/data)</span>
            <span className="val">Used {(stUsed / 1024).toFixed(1)} GB / {(stTotal / 1024).toFixed(1)} GB</span>
          </div>
          <div className="bar"><div className={`fill ${stUsed / stTotal > 0.85 ? "warn" : ""}`} style={{ width: `${stUsed / stTotal * 100}%` }} /></div>
        </div>
      </div>

      <div className="apps-toolbar">
        <div className="search">
          <Icon name="search" size={14} className="ico" />
          <input className="input" placeholder="Search by name or package…" value={query} onChange={(e) => setQuery(e.target.value)} />
        </div>
        <div className="seg">
          <button data-active={filter === "all"} onClick={() => setFilter("all")}>All</button>
          <button data-active={filter === "user"} onClick={() => setFilter("user")}>User</button>
          <button data-active={filter === "system"} onClick={() => setFilter("system")}>System</button>
        </div>
        <label className="h-stack" style={{ gap: 6, fontSize: 11, color: "var(--text-secondary)", cursor: "pointer" }}>
          <div className="cb" data-checked={showSystem} onClick={() => setShowSystem((s) => !s)} />
          Show system
        </label>
        <label className="h-stack" style={{ gap: 6, fontSize: 11, color: "var(--text-secondary)", cursor: "pointer" }}>
          <div className="cb" data-checked={showDisabled} onClick={() => setShowDisabled((s) => !s)} />
          Show disabled
        </label>
        <div style={{ marginLeft: "auto" }} className="h-stack">
          <span className="tag">{filtered.length} apps · {selected.size} selected</span>
          {selected.size > 0 &&
          <>
              <button className="btn sm danger"
            disabled={anySystemSelected}
            title={anySystemSelected ? "System apps can only be disabled" : ""}
            onClick={() => setConfirm({ kind: "uninstall", apps: selectedApps })}>
                <Icon name="trash" size={12} /> Uninstall
              </button>
              <button className="btn sm" disabled={!allActive}
            onClick={() => setConfirm({ kind: "disable", apps: selectedApps })}>
                Disable
              </button>
              <button className="btn sm" disabled={!allDisabled}
            onClick={() => setConfirm({ kind: "enable", apps: selectedApps })}>
                Enable
              </button>
            </>
          }
          <button className="btn sm ghost" data-comment-anchor="c729428fc9-button-118-11" style={{ display: "none" }} aria-hidden="true"></button>
          <button className="btn sm ghost icon-only" data-comment-anchor="68e5faadcb-button-119-11" style={{ display: "none" }} aria-hidden="true"></button>
        </div>
      </div>

      <div style={{ flex: 1, overflow: "auto" }}>
        <table className="table">
          <thead>
            <tr>
              <th style={{ width: 36 }}><div className="cb" data-checked={allSelected} onClick={toggleAll} /></th>
              <th>App Name</th>
              <th>Package</th>
              <th style={{ width: 110 }}>Type</th>
              <th style={{ width: 110 }}>Size</th>
              <th style={{ width: 110 }}>Status</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((a) =>
            <tr key={a.pkg}
            data-selected={selected.has(a.pkg)}
            className={a.status === "disabled" ? "row-disabled" : ""}
            onClick={() => toggleOne(a.pkg)}>
                <td><div className="cb" data-checked={selected.has(a.pkg)} /></td>
                <td>
                  <span style={{ fontWeight: 500 }}>{a.name}</span>
                </td>
                <td className="mono muted">{a.pkg}</td>
                <td><span className="pill">{a.type}</span></td>
                <td className="mono muted">{a.size} MB</td>
                <td>
                  {a.status === "active" ?
                <span className="pill online"><span className="pdot" />Active</span> :
                <span className="pill"><span className="pdot" />Disabled</span>}
                </td>
              </tr>
            )}
            {filtered.length === 0 &&
            <tr><td colSpan={6} style={{ textAlign: "center", padding: 40, color: "var(--text-muted)" }}>No apps match the current filter.</td></tr>
            }
          </tbody>
        </table>
      </div>

      {confirm &&
      <div className="modal-overlay" onClick={() => setConfirm(null)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="mhead">
              <h3>
                {confirm.kind === "uninstall" && "Uninstall apps?"}
                {confirm.kind === "disable" && "Disable apps?"}
                {confirm.kind === "enable" && "Enable apps?"}
              </h3>
            </div>
            <div className="mbody">
              <div style={{ marginBottom: 12 }}>
                {confirm.kind === "uninstall" && <>This will run <span className="tag">pm uninstall --user 0</span> for each app, sequentially. Only APK files can be backed up — app data cannot be saved without root.</>}
                {confirm.kind === "disable" && <>This will run <span className="tag">pm disable-user --user 0</span> for each app.</>}
                {confirm.kind === "enable" && <>This will run <span className="tag">pm enable</span> for each app.</>}
              </div>
              <div style={{ maxHeight: 120, overflow: "auto", border: "1px solid var(--border)", borderRadius: 4, padding: 8, background: "var(--surface-2)" }}>
                {confirm.apps.map((a) =>
              <div key={a.pkg} className="mono" style={{ fontSize: 11, padding: "2px 0", color: "var(--text-secondary)" }}>
                    {a.name} <span style={{ color: "var(--text-muted)" }}>— {a.pkg}</span>
                  </div>
              )}
              </div>
            </div>
            <div className="mfoot">
              <button className="btn ghost" onClick={() => setConfirm(null)}>Cancel</button>
              {confirm.kind === "uninstall" &&
            <button className="btn" onClick={() => doAction("uninstall")}>Back up & uninstall</button>
            }
              <button className={`btn primary ${confirm.kind === "uninstall" ? "danger" : ""}`}
            style={confirm.kind === "uninstall" ? { background: "var(--danger)", color: "#fff", boxShadow: "none" } : {}}
            onClick={() => doAction(confirm.kind)}>
                {confirm.kind === "uninstall" ? "Uninstall" : confirm.kind === "disable" ? "Disable" : "Enable"}
              </button>
            </div>
          </div>
        </div>
      }
    </div>);

};

window.AppsModule = AppsModule;
